spring:
  application:
    name: liaodd-backend
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 允许循环依赖
  main:
    allow-circular-references: true
  # session 配置
  session:
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.119.150.112:3306/liaodd_bi
    username: lds
    password: 159166
  # Redis 配置
  redis:
    database: 1
    host: 47.119.150.112
    port: 6379
    timeout: 5000
    password: 159166
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # rabbitmq配置
  rabbitmq:
    host: 47.119.150.112
    port: 5672
    username: lds
    password: 159166
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
yuapi:
  client:
    access-key: nhp159yfjmd9oo1c0763kvdbogqxfv6n
    secret-key: s2albqquqpw9vrqrxp1n5tlcfct8vx99
# 支付宝沙箱配置
pay:
  alipay:
    app-id: 9021000136670419
    app-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCng2nWO36NGMK5yyyZG+wQjU7uXk7gJkfVAYCu8dWyKCo6VehTJHKfre7IGwKC/4Wdg3hplYuWk5yfzZ9tOAVC39Px3tmIbXdT7Fotc306Akg/5GESxqAUbZtmezcXbVF90oyne7yr7A3LCs4A5B98k7HMO2NPiYoaVP2wUepaSNaoQa+757D6wrboTa5vL8DRu0mXF+H0t0HlTWCJh3H24DIbkY6RyAT8m82QJvN73dfGXcfcomvIKrXlnV2uv2DdgINTVL4HJBDdLdeWlJDE91aSw6Qk2BfZE1OudwoA+RGdb92H6p14D+pfU/EULxfOhwaTw2CLQfBmR6Pat4grAgMBAAECggEAQqaLCe6KH+HmOL6adCEkAEH5Uea8Q3t3wUzjwrf+avCIPMXJtqsd4GL4Sy5UBYNdyppw4rHZ5IO/IeZStMZBcaZVUjt1Gk9T11SHXOZCwT3/OUzJQws8zmP+HPyRowSgFAweYtVc8JrvsgYOiVQ7IvoxGC3ZCeCTzn5aojk1oc4L3lZhFgyLpNvoJZ3zy1WxKQR2V0j8IoJmoKBHQkcUwaVrroT61RurVgYTfIkWiydIVpkTi5VkhOkhQYb06B5dXt9uCRFrgG0vIVRY+f6DZATH36A5CfdxkvJtvY4rUTnXbboipid7EcoPUTQkWjGfAOq0y8cYBKsw6r29kLvtwQKBgQDkyfdDIek7ujpATne6Bn4BK2/nMSjSey1/Yj/e/nOUlwZ+lzZDrZcznAGPdCNgv7hIV4P0n0FkKGb9YRGYC1j3Dif/Sl9cLkHO4FFR1P/62jwkzL6TqldTS+pAgWdlEd9DZlZqcuwNZz8ptFHmps0RoV7QlsdliojeLq6jY0hhUwKBgQC7b8Nrk4mnJnZZmtYPBXHkGsrIMCQKiB8hjfD1PxFITIwraIwNaeFAut624LX8LAw8egdleV/FqtyYuO4KXptBgceuAnHwxXBDBfomCFmCnE7FgKsXNiEmd4XS0Bw9xzD34n8xp9e2f5WkAh0fI4lIPhrXo0D6xQBUkHBu3naqyQKBgQDKIp5xE47rFDfPBQTGuGGvSt9NVaOJgwbJmtZvgERBrcUxJwvsc3w5PsYqJiPzoK+CSr/s6p9tjDyh9JcEzFHHxRwVc3IZEU1XJ9zw/c1Dpnio0rQ15rPMhi/q2emt5EJrXAlRd0OS+/tUL1qE/C4GO5p3lB+LWQBfvMLS3C7gvQKBgQCVE0L+II3u32xpv/hYYiA/J//4UDGaHsGD0ny+0bZRJnClZbVeRcPd08Km+PpE4lOpFfUkA/DkKgzhetP4c15QL4Q9Jbyxnpa2994IucNXWjJcawWopGihS5aoINUVXYPY48/+ElxCzh6aHwRCa+UYDC0VLMbVrDGjEG4b/9up4QKBgQDXiQlHQMCTMJgxtG+PWVE43bR3n/Z9BBtefhnxMvRIEFZWvokQlDOiyv10TlYr7p1nZ+pM6EpvAoQAfEica0lCE5qaHVcCWsCCxdaMqI8tVLDCbFPLW4kAMU2eO4HoNR18CRaoCOI4ex5+2jzujRDHv7xm4TGH2vANZtDKVUGsTw==
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiLeZq2pHMGFoMbK+V0EJJC29YI1QBY6FMNglLLoy9RoUl57YyqQl5PWfB/Uk/IPocKfi6dPO9S7lkEeGNkMZ4f9g4l0MOfJmGGiwIuqCzkiNBBUNyuS3SMR9pTo/tybESP29J04l12VyxLX4C//seZ0HxBHdaIvC+anG/1+2T3glOuJvpSYz3CAEvtyV3PYEv/r2mvtEbgjeO1pLz49+SX5Y50Uw9O4T6xT2auI6B6YWvOGL38TXtfQIutptlo1Jj/UDsyStX9quAAdzmV3vIwAKCNkECFU0K3yoI8XbTl2ICif48dfxfr8HIFulmZd1SFYmj9iyL+pcwzqUiSA4HwIDAQAB
    notify-url: http://47.119.150.112:8101/api/alipay/tradeQuery?alipayAccountNo=%s
  er:
    url: http://47.119.150.112:8101/api/alipay/pay?orderId=%s&userId=%s